### ISSUE TITLE
Asignación de trabajo

### ISSUE THREAD

**Issue by xeleh** [amicoders/megademo#2]
Mejor que tocar el readme cada vez, que cada persona que quiera participar deje un comentario aquí con el efecto o parte del proyecto del que se quiere ocupar, y a ser posible algún link o referencia para que podamos hacernos una idea aproximada de lo que tiene en mente. Os recuerdo que no vale asignarse efectos que ya tengáis programados, pues la idea es forzarnos a programar cosas nuevas.

Si alguien quiere iniciar discusiones sobre un efecto concreto (ya sea implementación, ideas o lo que sea) propongo que no lo haga aquí, sino que abra una issue aparte para eso. La razón es puramente organizativa: básicamente tener cada cosa en su lugar y poder cerrar esta issue una vez consideremos que tenemos todo el trabajo asignado.

**Comment by xeleh** [comment]
**Fractal Zoomer**: El más bonito que he visto es el de la intro Chaosland de Virtual Dreams: https://youtu.be/A9n_D0wvA1I?t=15s

Aparte de eso ayudaré en temas de construcción, código base y organización en general.

**Comment by m6502** [comment]
Dots are my favours https://youtu.be/jziQBWQxvok?t=341

**Comment by nandiusc** [comment]
**Vectorballs** para mí, aunque no acabo de encontrar un ejemplo que realmente me guste o me llame la atención, salvo los "vectorcubes": https://youtu.be/MHH1zu_ZAec?t=815. 

Y llevo casi 5 años dándole al asm para OCS casi sin pausa, así que encantado de echar un cable con cualquier otra cosa, en la medida de mis posibilidades.

**Comment by SkynetAmiga** [comment]
Yo quiero hacer unos transforming vectors como los de la Hardwired
[https://youtu.be/2CGOh-jb4QM?t=281]

El efecto en sí es una chorrada con los planos para el rastro, pero lo que me mola es hacer una transformación entre objetos currada.
