### ISSUE TITLE
Temática y nombre

### ISSUE THREAD

**Issue by xeleh** [amicoders/megademo#3]
RFC para que decidamos esto lo antes posible, pues aunque para hacer los efectos no es tampoco vital, sí que será importante para el diseño gráfico, el menú y quizás hasta para hacer la música.

**Comment by m6502** [comment]
Dinocoder xD

**Comment by xeleh** [comment]
Mejor si desarrollamos un poco las propuestas. Con un párrafo o una referencia a algo parecido nos vale, tampoco hace falta escribir El Quijote.
